// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5uGPjcouG7Xovfpe_FggNLgvrtnmZrc',
    appId: '1:233119449462:web:4fb312158fbb9e918cfa57',
    messagingSenderId: '233119449462',
    projectId: 'bookapp-2cf1b',
    authDomain: 'bookapp-2cf1b.firebaseapp.com',
    storageBucket: 'bookapp-2cf1b.firebasestorage.app',
    measurementId: 'G-TBGC3GKKVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbi93BduYaMFqF4smJFfdlU-zCTjmK4vk',
    appId: '1:233119449462:android:14673573f5309d0b8cfa57',
    messagingSenderId: '233119449462',
    projectId: 'bookapp-2cf1b',
    storageBucket: 'bookapp-2cf1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbgBF5jPiyE1-ilmhQvpQjkge7TdgIoc',
    appId: '1:233119449462:ios:4db7779d1f2d36658cfa57',
    messagingSenderId: '233119449462',
    projectId: 'bookapp-2cf1b',
    storageBucket: 'bookapp-2cf1b.firebasestorage.app',
    iosBundleId: 'com.clover.wareed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbgBF5jPiyE1-ilmhQvpQjkge7TdgIoc',
    appId: '1:233119449462:ios:5f3c543717eeb7178cfa57',
    messagingSenderId: '233119449462',
    projectId: 'bookapp-2cf1b',
    storageBucket: 'bookapp-2cf1b.firebasestorage.app',
    iosBundleId: 'com.example.bloody',
  );
}
